### PR TITLE
Documented fly clear-resource-cache

### PR DESCRIPTION
**Pull request by EstebanFS**
Documented fly clear-resource-cache

related: concourse/concourse#7003

Signed-off-by: Esteban Foronda <eforonda@vmware.com>

### CODE REVIEW

**Comment by muntac** [comment]
cc: @clarafu

**Review by clarafu — APPROVED** [review]
LGTM! 👍  You can merge this as soon as the original PR is merged

**Review by taylorsilva — APPROVED** [review]
approving on behalf of Clara

**Comment by taylorsilva** [comment]
Probably shouldn't merge until concourse/concourse#7003 is merged

**Pull request merged**
